name: Deploy
on:
  push:
    branches:
      - dev
      - test
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare SSH
      env:
        SECRETS: ${{ toJson(secrets) }}
      run: |
        mkdir ~/.ssh
        BRANCH=${GITHUB_REF##*/}
        echo $SECRETS | jq -r '.DEPLOY_KEY_'${BRANCH^^} > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa

    - name: Checkout project
      uses: actions/checkout@master

    - name: Prepare Deployer
      run: |
        composer create-project --no-interaction aonach/ghactions-deploy:dev-master deployer

    - name: Deploy project
      run: |
        CONFIG_PATH=$([ -f deploy.php ] && echo '.' || echo './deployer')
        deployer/vendor/bin/dep \
          --file=$CONFIG_PATH/deploy.php \
          --repository=git@github.com:$GITHUB_REPOSITORY.git \
          --revision=$GITHUB_SHA \
          -vvv \
          deploy ${GITHUB_REF##*/}
