dev:
  hostname: dev-host
  user: dev-user
  deploy_path: ~/dev-deploy
  repo_path: src

test:
  hostname: test-host
  user: test-user
  deploy_path: ~/test-deploy
  repo_path: src

master:
  hostname: master-host
  user: master-user
  deploy_path: ~/master-deploy
  repo_path: src
